### PR TITLE
Adjustments regarding the new solph structure

### PR DESCRIPTION
**Pull request by fwitte**

### CODE REVIEW

**Comment by simnh** [comment]
@eosram @gnn can you please check ?

**Comment by gnn** [comment]
Sorry for taking so long. I'm not ready to approve this yet for two reasons:

  - I still have to get `oemof.network` out of release candidate status, which entails moving a lot of classes back into the `oemof.network` module, which means a lot of the import adjustments can be rolled back.
  - I still have questions about some of the adjustments.

**Comment by simnh** [comment]
Ah yeah there is also still a problem thats maybe linked to the network module: 

```
/home/admin/projects/oemof-jordan/jordan-env/lib/python3.6/site-packages/oemof/solph/network.py:263: SuspiciousUsageWarning: `Source` 'Aqaba1' constructed without `outputs`.
```

This similar warning actually happens for every components being instantiated in the one way or another.

**Comment by uvchik** [comment]
You should switch off the SuspiciousUsageWarning. This was a compromise between solph and tabular. For most solph users it is an error if they construct a Source without an output or a Sink without an input. If the user just misspell the respective attribute it was hard to find the bug. So we invented the `SuspiciousUsageWarning` to make it easier for them to find such bug.

But it is allowed to construct a Source without an output and add the output later. In solph this is very rare but it is the way you construct nodes in tabular. Therefore, we do not raise an error and we added a specific warning that do not effect other warnings if you switch it off (see [Handling of Warnings](https://oemof-solph.readthedocs.io/en/latest/usage.html#handling-of-warnings ) in the solph docs).

**Comment by unndreay** [comment]
Hey! We are using tabular in https://github.com/modex-flexmex/oemo-flex/ and wait for it to get working with oemof-solph 0.4.x. Since I am not familiar with the background, I couldn't see what's the progress or what solution is needed. Can we help at some point or take action ourselves? Thank you!

**Comment by simnh** [comment]
@uvchik Thanks for the hint with the warning! 

@unndreay Yeah acutually most of the work has been done. The warning stuff that @uvchik mentioned has to be done. And I guess some final checks. You could help be dealing with the warning

Also @gnn wanted to transfer some code from anther dependency to this package which is kind of important. So it would be great if you @gnn would finalize this PR (which is pending for quite a while....)

I used the version for some projects already, and I am sure everthing works as intended.

**Comment by simnh** [comment]
> Hey! We are using tabular in https://github.com/modex-flexmex/oemo-flex/ and wait for it to get working with oemof-solph 0.4.x. Since I am not familiar with the background, I couldn't see what's the progress or what solution is needed. Can we help at some point or take action ourselves? Thank you!

dfg

**Comment by simnh** [comment]
> Hey! We are using tabular in https://github.com/modex-flexmex/oemo-flex/ and wait for it to get working with oemof-solph 0.4.x. Since I am not familiar with the background, I couldn't see what's the progress or what solution is needed. Can we help at some point or take action ourselves? Thank you!

You could try to fix the stuff that causes the checks to fail :-) (if that possible for you)

**Comment by jnnr** [comment]
> @uvchik Thanks for the hint with the warning!
> 
> @unndreay Yeah acutually most of the work has been done. The warning stuff that @uvchik mentioned has to be done. And I guess some final checks. You could help be dealing with the warning

It sounds like we should switch off the SuspiciousUsageWarning for oemof.tabular. This should not be too much work - probably somewhere centrally?

> Also @gnn wanted to transfer some code from anther dependency to this package which is kind of important. So it would be great if you @gnn would finalize this PR (which is pending for quite a while....)

Can this be done in a separate PR? 

> I used the version for some projects already, and I am sure everthing works as intended.

So this branch is already tested in practice. Great!

**Comment by jnnr** [comment]
With 1922cd9, I switched off the SuspiciousUsageWarnings in the facades module. If you think that it should be switched off at a different place, please correct. I tested it with the example compute.py and could get rid of the warnings.

**Comment by jnnr** [comment]
We can now test this branch with our model runs for any errors. Will give feedback here. Only remaining thing is the travis check.

**Comment by jnnr** [comment]
While reviewing, I noticed that commit cb1ce4d (introducing capacity_minimum) seems a bit unrelated to this PR. Wrong branch?

**Comment by simnh** [comment]
> While reviewing, I noticed that commit [cb1ce4d](https://github.com/oemof/oemof-tabular/commit/cb1ce4d508c78e25ff903d864eb7cdf49e119ac9) (introducing capacity_minimum) seems a bit unrelated to this PR. Wrong branch?

Yeah, should have been on dev...mh. maybe we can keep it here for now? I do not have time to clean this up. But I would really like to get the next version of oemof-tabular out there, which is working on 0.4 solph

**Comment by simnh** [comment]
@gnn can you check this branch as well? so we can continue on dev....and release...should also be important for open-modex I guess?

**Comment by jnnr** [comment]
> > While reviewing, I noticed that commit [cb1ce4d](https://github.com/oemof/oemof-tabular/commit/cb1ce4d508c78e25ff903d864eb7cdf49e119ac9) (introducing capacity_minimum) seems a bit unrelated to this PR. Wrong branch?
> 
> Yeah, should have been on dev...mh. maybe we can keep it here for now? I do not have time to clean this up. But I would really like to get the next version of oemof-tabular out there, which is working on 0.4 solph

Directly on dev :scream: ? I remember a meme for that :) ... Anyway, I am ok to keep it here if it would eventually end up in dev anyway.

Just some human and machine checks to pass - hopefully we can finish this soon!

**Comment by jnnr** [comment]
Any news here? Only the failing checks are still open. I found an import error in one example (fixed in 0609ea0). 

I ran tox locally. There seem to be still a problem with codecov. And an error with the jupyter notebook environments. Can someone help?

**Comment by simnh** [comment]
@gnn could you check thiss and we finalise this PR?

**Comment by gnn** [comment]
On it. Sorry for being a blocker on this for far too long. I fixed the `tox -e check` fails. Don't know whether I can fix the `ipython` stuff or the other build errors, but I'll have a look at it and request assistance if I can't fix the errors myself.

**Comment by MaGering** [comment]
I also wanted to check if this PR could be merged soon? Tests fail on my branch https://github.com/rl-institut/oemof-B3/pull/76 because of an incompatibility error of pandas caused by `oemof.tabular`'s installation of `oemof` (cf. [this comment](https://github.com/rl-institut/oemof-B3/pull/76#issuecomment-1013026677)).

**Pull request merged**
